version: '3.7'

services:
  oj-minio:
    image: minio/minio
    container_name: oj-minio-test
    command: server /data
    restart: always
    volumes:
      - ./data/test/minio:/data

  oj-mongo:
    image: mongo:4-focal
    container_name: oj-mongo-test
    restart: always
    volumes:
      - ./data/test/mongo:/data/db

  oj-elastic:
    image: elasticsearch:8.0.1
    container_name: oj-elastic-test
    restart: always
    volumes:
      - ./data/test/elastic:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_SETTING_XPACK_SECURITY_ENABLED=false
    ports:
      - 9200:9200

  oj-backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile-test
    container_name: oj-backend-test
    restart: always
    depends_on:
      - oj-minio
      - oj-mongo
      - oj-elastic
    volumes:
      - ./config/backend:/root/.hydro
    ports:
      - "0.0.0.0:80:8888"

  oj-judge:
    build:
      context: ..
      dockerfile: docker/judge/Dockerfile-test
    container_name: oj-judge-test
    restart: always
    privileged: true
    volumes:
      - ./config/judge:/root/.config/hydro
    shm_size: '1536mb'
