name: Docker

on:
  push:
    branches: ["master"]

env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: false
  REGISTRY: registry.cn-hangzhou.aliyuncs.com

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: stagoh
          password: ${{ secrets.ALIYUN_DOCKER }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies & Build Hydro
        run: |
          yarn install
          yarn build:ui:production

      - name: Extract metadata (tags, labels) for Backend Image
        id: b_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/jgsu-acm/backend

      - name: Extract metadata (tags, labels) for Judge Image
        id: j_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/jgsu-acm/judge

      - name: Build and push Docker image Backend
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/jgsu-acm/backend:latest
          labels: ${{ steps.b_meta.outputs.labels }}
          file: docker/backend/Dockerfile
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}

      - name: Build and push Docker image Judge
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/jgsu-acm/judge:latest
          labels: ${{ steps.j_meta.outputs.labels }}
          file: docker/judge/Dockerfile
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
